### ISSUE TITLE
Feature request: identifiers and fields option

### ISSUE THREAD

**Issue by Tink-** [smilledge/node-google-books-search#1]
Dear smilledge,

This module is awesome! However, I would like to suggest an additional feature, if you're open to that. It would be nice to add the fields-options to the search options, so the fields that are shown, can be selected by users. The identifiers field, for example, is not shown by default.

Thanks for the superb module,
Kind regards,
Tink

**Comment by smilledge** [comment]
I've just pushed a new version to NPM which should address these issues. 

This should now be returning all the useful field by default (including identifiers). I'm still excluding the access and sale info provided by Google as I assume this will be irrelevant for most projects. However, if someone does need access to this data it can be accessed via the third callback parameter which now contains the raw API response from Google.

Hopefully this is helpful, and sorry for taking so long to update this package.
